drop table movies;
drop table ratings;

CREATE TABLE movies (movieid string, moviename string, genre string) ROW FORMAT DELIMITED FIELDS TERMINATED BY "#" LINES TERMINATED BY "\n";
CREATE TABLE ratings (userid string,movieid string,rating float,time_stamp timestamp) ROW FORMAT DELIMITED FIELDS TERMINATED BY "#" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INPATH "/tmp/Fall2014_HW-3_Hive/movies_new.dat" INTO TABLE movies;
LOAD DATA LOCAL INPATH "/tmp/Fall2014_HW-3_Hive/ratings_new.dat" INTO TABLE ratings;

SELECT m.movieid, m.moviename, m.genre, avg(r.rating) AS avg_rating FROM movies m JOIN ratings r ON m.movieid = r.movieid WHERE m.genre like "%Action%"  GROUP BY m.movieid, m.moviename, m.genre ORDER BY avg_rating DESC LIMIT 11;